### ISSUE TITLE
InterfaceConfig needs a field called ifname and a field called name

### ISSUE THREAD

**Issue by pmelange** [freifunk-berlin/falter-ffwizard_spec#1]
currently there is only the "name" field for interfaces.  This is confusing as I was expecting things such as "dhcp" "wan" "meshlan".  But instead there are values like "eth0.1" "eth0.2".  I would consider "eth0.1" in ifname and "dhcp" as the name.

**Comment by akira25** [comment]
That was fixed by 8b44d92 too. thanks for pointing out. :)
